module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    holyiot: require('./holyiot'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mountinghole: require('./mountinghole'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    rawkicad: require('./rawkicad'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    tactswitch: require('./tactswitch'),
    tentingpuck: require('./tentingpuck'),
    trace: require('./trace'),
    trrs: require('./trrs'),
    usbc: require('./usbc'),
    via: require('./via'),
    xiao: require('./xiao'),
}